In [24]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/youtube.csv",index_col=0)
#df.head()

answer =list(df.loc[df.channelId.isin(df.channelId.value_counts().head(10).index)].channelTitle.unique())
#print(answer)
df['answer1'] = df['dislikes'] > df['likes']
answer2 = df.groupby('channelTitle')['answer1'].any()
answer3 = answer2[answer2].index.tolist()
answer3

['(MUTUBE)와꾸대장봉준',
 'ASMR 애정TV',
 'Gen.G esports',
 'MapleStory_KR',
 'ROAD FIGHTING CHAMPIONSHIP',
 '나혼자산다 STUDIO',
 '사나이 김기훈',
 '양팡 YangPang',
 '오메킴TV',
 '왜냐맨하우스',
 '육지담',
 '철구형 (CHULTUBE)',
 '하얀트리HayanTree',
 '핫도그TV']

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60399 entries, 0 to 60398
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           60399 non-null  object
 1   channelTitle    60399 non-null  object
 2   categoryId      60399 non-null  int64
 3   view_count      60399 non-null  int64
 4   likes           60399 non-null  int64
 5   dislikes        60399 non-null  int64
 6   comment_count   60399 non-null  int64
 7   channelId       60399 non-null  object
 8   trending_date2  60399 non-null  object
dtypes: int64(5), object(4)
memory usage: 4.6+ MB

In [26]:
display(channel.head())
display(video.head())

,channelid,subcnt,viewcnt,videocnt,ct,channelname
0,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,410238653,736,2021-09-30 03:01:03,꽈뚜룹
1,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,412531322,736,2021-09-30 09:01:03,꽈뚜룹
2,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,412531322,735,2021-09-30 15:01:03,꽈뚜룹
3,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,412531322,737,2021-09-30 21:01:03,꽈뚜룹
4,UCkQCwnkQfgSuPTTnw_Y7v7w,1320000,412531322,737,2021-10-01 03:01:04,꽈뚜룹

,videopk,viewcnt,likecnt,dislikecnt,favoritecnt,cmcnt,ct,videoname
0,c5JQp6xafqc,1667010,30474,706,0,6587,2021-10-10 15:20:03,공범 EP1
1,c5JQp6xafqc,1669089,30495,707,0,6589,2021-10-10 15:30:03,공범 EP1
2,c5JQp6xafqc,1674759,30522,711,0,6596,2021-10-10 15:40:02,공범 EP1
3,c5JQp6xafqc,1677026,30555,712,0,6604,2021-10-10 15:50:03,공범 EP1
4,c5JQp6xafqc,1681824,30585,713,0,6600,2021-10-10 16:00:03,공범 EP1

In [ ]:
import pandas as pd


channel =pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/channelInfo.csv')
video =pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/videoInfo.csv')
#channel.info(), video.info()
channel['ct'] = pd.to_datetime(video['ct'])
answer = video.videoname.value_counts()
print(answer)

videoname
공범 EP1    3492
공범 EP2    3204
공범 EP3    2568
공범 EP4    2280
공범 EP5    1562
공범 EP6    1274
공범 EP7     555
공범 EP8     266
Name: count, dtype: int64